# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: deificx.github.io
email: even@alander.org
description: > # this means to ignore newlines until "baseurl:"
  A collection of my github projects that I find share-worthy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: iameven
github_username:  deificx

# Build settings
markdown: kramdown
